"""Remove transient Jupyter notebook fields that create noisy diffs.

The cleaner preserves notebook source, outputs, execution counts, and top-level
metadata, but drops per-cell ids and execution timing metadata. These fields are
regenerated by frontends/runtimes and are not useful in version control.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

TRANSIENT_CELL_METADATA = {"execution"}


def clean_notebook(path: Path) -> bool:
    """Clean a notebook in place.

    Returns True when the file content changed.
    """
    before = path.read_text()
    notebook: dict[str, Any] = json.loads(before)

    for cell in notebook.get("cells", []):
        cell.pop("id", None)
        metadata = cell.get("metadata")
        if isinstance(metadata, dict):
            for key in TRANSIENT_CELL_METADATA:
                metadata.pop(key, None)
            if not metadata:
                cell["metadata"] = {}

    after = json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"
    if after != before:
        path.write_text(after)
        return True
    return False


def iter_notebooks(paths: list[Path]) -> list[Path]:
    notebooks: list[Path] = []
    for path in paths:
        if path.is_dir():
            notebooks.extend(sorted(path.rglob("*.ipynb")))
        elif path.suffix == ".ipynb":
            notebooks.append(path)
    return notebooks


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Strip transient cell ids and execution metadata from notebooks."
    )
    parser.add_argument(
        "paths",
        nargs="+",
        type=Path,
        help="Notebook files or directories to clean.",
    )
    args = parser.parse_args(argv)

    changed = 0
    for notebook in iter_notebooks(args.paths):
        if clean_notebook(notebook):
            changed += 1
            print(f"cleaned {notebook}")

    print(f"Cleaned {changed} notebook(s).")


if __name__ == "__main__":
    main()
